### ISSUE TITLE
Null-safety support

### ISSUE THREAD

**Issue by Coezette** [cholojuanito/credit_card_type_detector#3]
Hi, 

Will you be adding Null-safety support to make the package compatible with Flutter 2?

**Comment by cholojuanito** [comment]
Already done!

https://pub.dev/packages/credit_card_type_detector/versions/2.0.0-nullsafety.0

I forgot to make a release for it on GitHub but it's there on pub.dev

**Comment by Coezette** [comment]
Awesome job.

**Comment by Crewlan** [comment]
when will you switch dart version from dev to stable? @cholojuanito

**Comment by cholojuanito** [comment]
@Crewlan Not sure what you're referring to.

**Comment by Crewlan** [comment]
@cholojuanito  in pub.dev https://pub.dev/packages/credit_card_type_detector/versions show dart 2.12(dev).. my question is this lib not in stable channel?


Because I go to use in my actual project and the warning don't disappear

**Comment by cholojuanito** [comment]
@Crewlan So that is for the null safe version of the package. You need to be on that dart channel in order to have null-safety.
See https://dart.dev/null-safety#constraints for what I am talking about.

If your project is trying to use null safety I'm pretty sure you need to have those same Dart SDK constraints. I'll look into it more to see if I can update those constraints now that null safety is the default in Flutter.

**Comment by cholojuanito** [comment]
~Ah, I see. I think I just need to push a package version that doesn't have the "nullsafety" suffix.~
Never mind, I think I found the issue. I'll get working on it

**Comment by cholojuanito** [comment]
@Crewlan I think I have fixed it. There is now an "official" release version that uses null safety instead of a pre-release. And the SDK constraints were changed so it is no longer labelled as 2.12(dev)
